AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  ResourcePrefix:
    Description: Prefix to prepend to all AWS resource names
    Type: String
  LemmyURL:
    Type: String
  LemmyUser:
    Type: String
  LemmyPass:
    Type: String
  KnownPaywalls:
    Type: String
    
Resources:
  LemmyFeederFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ['-', [!Ref ResourcePrefix, 'lemmy-feeder']]
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 300
      Environment:
        Variables:
          LEMMY_URL: !Ref LemmyURL
          LEMMY_USER: !Ref LemmyUser
          LEMMY_PASS: !Ref LemmyPass
          KNOWN_PAYWALLS: !Ref KnownPaywalls
  LemmyFeederPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LemmyFeederFunction.Arn
      Principal: !Ref AWS::AccountId
      Action: lambda:InvokeFunction
