name: Build and Deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - develop
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      RESOURCE_PREFIX: ${{ secrets.RESOURCE_PREFIX }}
      LEMMY_URL: ${{ secrets.LEMMY_URL }}
      LEMMY_JWT: ${{ secrets.LEMMY_JWT }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::388474961170:role/github-actions-oidc
          aws-region: us-east-1

      - name: Build and deploy
        run: |
          sam build --use-container
          sam package --s3-bucket deploy.harrison.enterprises --output-template-file ./packaged.yaml --region us-east-1
          sam deploy --template-file ./packaged.yaml --stack-name "fp-lemmy-feeder" --capabilities CAPABILITY_IAM --region us-east-1 --no-fail-on-empty-changeset --parameter-overrides "LemmyURL=$LEMMY_URL,LemmyJWT=$LEMMY_JWT,ResourcePrefix=$RESOURCE_PREFIX"
