name: Build and Deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - develop
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEPLOY_BUCKET: ${{ vars.AWS_DEPLOY_BUCKET }}
      AWS_DEPLOY_REGION: ${{ vars.AWS_DEPLOY_REGION }}
      AWS_RESOURCE_PREFIX: ${{ vars.AWS_RESOURCE_PREFIX }}
      LEMMY_URL: ${{ vars.LEMMY_URL }}
      LEMMY_USER: ${{ vars.LEMMY_USER }}
      LEMMY_PASS: ${{ secrets.LEMMY_PASS }}
      KNOWN_PAYWALLS: ${{vars.KNOWN_PAYWALLS}}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE }}
          aws-region: ${{ vars.AWS_DEPLOY_REGION }}

      - name: Build and deploy
        run: |
          sam build --use-container
          sam package --s3-bucket "$AWS_DEPLOY_BUCKET" --output-template-file ./packaged.yaml --region "$AWS_DEPLOY_REGION"
          sam deploy --template-file ./packaged.yaml --stack-name "$AWS_RESOURCE_PREFIX"-lemmy-feeder --capabilities CAPABILITY_IAM --region "$AWS_DEPLOY_REGION" --no-fail-on-empty-changeset --parameter-overrides LemmyURL="$LEMMY_URL" LemmyUser="$LEMMY_USER" LemmyPass="$LEMMY_PASS" ResourcePrefix="$AWS_RESOURCE_PREFIX" KnownPaywalls="$KNOWN_PAYWALLS"
